# Generated by Django 3.1.2 on 2020-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_ID', models.CharField(max_length=20)),
                ('Roll_no', models.CharField(max_length=20)),
                ('Class_ID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_ID', models.CharField(max_length=20)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.CharField(max_length=10)),
                ('Semester', models.IntegerField()),
                ('Course_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_ID', models.CharField(max_length=20)),
                ('Dept_HOD', models.CharField(max_length=50)),
                ('Dept_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_ID', models.CharField(max_length=20)),
                ('Exam_date', models.DateField()),
                ('Exam_Time', models.TimeField()),
                ('Exam_Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_ID', models.CharField(max_length=20)),
                ('Fac_Name', models.CharField(max_length=50)),
                ('Date_of_Joining', models.DateField()),
                ('Position', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.CharField(max_length=10)),
                ('Roll_no', models.CharField(max_length=20)),
                ('Grade', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.CharField(max_length=20)),
                ('Faculty_ID', models.CharField(max_length=20)),
                ('Course_ID', models.CharField(max_length=10)),
                ('Exam_ID', models.CharField(max_length=20)),
                ('Dept_ID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.CharField(max_length=20)),
                ('Stu_Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Section', models.CharField(max_length=8)),
                ('Mobile', models.CharField(max_length=11)),
                ('Email_ID', models.EmailField(max_length=50)),
                ('Area', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=20)),
            ],
        ),
    ]
