# Generated by Django 3.1.1 on 2020-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allot_Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Startdate', models.DateField()),
                ('Enddate', models.DateField()),
                ('Number_of_Exams', models.IntegerField()),
                ('Department_ID', models.CharField(max_length=20)),
                ('Tdy_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
