# Generated by Django 3.1.1 on 2020-11-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20201124_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=30)),
                ('Exam_ID', models.CharField(max_length=20)),
                ('Exam_date', models.DateField()),
                ('Exam_Time', models.TimeField()),
                ('Exam_Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
