# Generated by Django 3.1.1 on 2020-11-27 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201124_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='allot',
            name='Faculty_ID',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
