# Generated by Django 3.1.1 on 2020-11-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_allot_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allot',
            name='Faculty_ID',
            field=models.CharField(max_length=40),
        ),
    ]
